version: '3'

services:
  backup:
    build:
      context: .
    restart: always
    ports:
      - "127.0.0.1:${BACKEND_PORT}:6000"
    volumes:
      - ${EXTERNAL_IMAGES_PATH}:/app/images
      - ${EXTERNAL_COMPRESS_FILES_PATH}:/app/compress_files
    networks:
      - blogdb

networks:
  blogdb:
    external: true
